# Generated by Django 5.1 on 2024-08-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_location', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('travel_date', models.DateField()),
                ('travel_time', models.TimeField()),
                ('details', models.TextField()),
            ],
        ),
    ]
