# Generated by Django 5.1 on 2024-08-17 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Itinerary',
        ),
    ]
